{
 "title": "FMADIO Prometheus",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "host", "label": "Host", "query": { "query": "label_values(instance)" } }
  ]
 },
 "panels": [
  { "title": "FMADIO System Information", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Capture Rate (bps)",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "fmadio_capture_rate_bps{instance=\"$host\"}",
     "legendFormat": "Capture Rate"
    }
   ]
  },
  {
   "title": "FMADIO Version",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "fmadio_ver{instance=\"$host\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "h" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "fmadio_other_UptimeHour{instance=\"$host\"}",
     "legendFormat": "Uptime"
    }
   ]
  },
  {
   "title": "Capture Byte",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "fmadio_capture_byte{interface=\"all\", instance=\"$host\"}",
     "legendFormat": "ALL"
    },
    {
     "expr": "fmadio_capture_byte{interface=\"cap0\", instance=\"$host\"}",
     "legendFormat": "CAP0"
    },
    {
     "expr": "fmadio_capture_byte{interface=\"cap1\", instance=\"$host\"}",
     "legendFormat": "CAP1"
    },
    {
     "expr": "fmadio_capture_byte{interface=\"cap2\", instance=\"$host\"}",
     "legendFormat": "CAP2"
    },
    {
     "expr": "fmadio_capture_byte{interface=\"cap3\", instance=\"$host\"}",
     "legendFormat": "CAP3"
    },
    {
     "expr": "fmadio_capture_byte{interface=\"cap4\", instance=\"$host\"}",
     "legendFormat": "CAP4"
    },
    {
     "expr": "fmadio_capture_byte{interface=\"cap5\", instance=\"$host\"}",
     "legendFormat": "CAP5"
    },
    {
     "expr": "fmadio_capture_byte{interface=\"cap6\", instance=\"$host\"}",
     "legendFormat": "CAP6"
    },
    {
     "expr": "fmadio_capture_byte{interface=\"cap7\", instance=\"$host\"}",
     "legendFormat": "CAP7"
    }
   ]
  },
  {
   "title": "Capture Rate (Packets)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "fmadio_capture_pkt{interface=\"all\", instance=\"$host\"}",
     "legendFormat": "All"
    },
    {
     "expr": "fmadio_capture_pkt{interface=\"cap0\", instance=\"$host\"}",
     "legendFormat": "Cap0"
    },
    {
     "expr": "fmadio_capture_pkt{interface=\"cap1\", instance=\"$host\"}",
     "legendFormat": "Cap1"
    },
    {
     "expr": "fmadio_capture_pkt{interface=\"cap2\", instance=\"$host\"}",
     "legendFormat": "Cap2"
    },
    {
     "expr": "fmadio_capture_pkt{interface=\"cap3\", instance=\"$host\"}",
     "legendFormat": "Cap3"
    },
    {
     "expr": "fmadio_capture_pkt{interface=\"cap4\", instance=\"$host\"}",
     "legendFormat": "Cap4"
    },
    {
     "expr": "fmadio_capture_pkt{interface=\"cap5\", instance=\"$host\"}",
     "legendFormat": "Cap5"
    },
    {
     "expr": "fmadio_capture_pkt{interface=\"cap6\", instance=\"$host\"}",
     "legendFormat": "Cap6"
    },
    {
     "expr": "fmadio_capture_pkt{interface=\"cap7\", instance=\"$host\"}",
     "legendFormat": "Cap7"
    }
   ]
  },
  {
   "title": "CPU Load",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "fmadio_system_cpu{instance=\"$host\"}",
     "legendFormat": "CPU"
    }
   ]
  },
  {
   "title": "Capture Drop",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "decbits" } },
   "targets": [
    {
     "expr": "fmadio_capture_drop{interface=\"all\", instance=\"$host\"}",
     "legendFormat": "Capture Drop"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "fmadio_system_memfree{instance=\"$host\"}",
     "legendFormat": "Mem Free"
    },
    {
     "expr": "fmadio_other_MemBuffer{instance=\"$host\"}",
     "legendFormat": "Mem Buffer"
    },
    {
     "expr": "fmadio_other_MemCached{instance=\"$host\"}",
     "legendFormat": "Mem Cache"
    },
    {
     "expr": "fmadio_other_MemDirty{instance=\"$host\"}",
     "legendFormat": "Mem Dirty"
    },
    {
     "expr": "fmadio_other_MemErrorECC{instance=\"$host\"}",
     "legendFormat": "Mem ECC Error"
    },
    {
     "expr": "fmadio_other_MemMapped{instance=\"$host\"}",
     "legendFormat": "Mem Map"
    }
   ]
  },
  {
   "title": "Fan Speed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
   "targets": [
    {
     "expr": "fmadio_fan_system{interface=\"SYS0\", instance=\"$host\"}",
     "legendFormat": "SYS0"
    },
    {
     "expr": "fmadio_fan_system{interface=\"SYS1\", instance=\"$host\"}",
     "legendFormat": "SYS1"
    },
    {
     "expr": "fmadio_fan_system{interface=\"SYS2\", instance=\"$host\"}",
     "legendFormat": "SYS2"
    },
    {
     "expr": "fmadio_fan_system{interface=\"SYS3\", instance=\"$host\"}",
     "legendFormat": "SYS3"
    },
    {
     "expr": "fmadio_fan_system{interface=\"SYS4\", instance=\"$host\"}",
     "legendFormat": "SYS4"
    },
    {
     "expr": "fmadio_fan_system{interface=\"SYS5\", instance=\"$host\"}",
     "legendFormat": "SYS5"
    },
    {
     "expr": "fmadio_fan_system{interface=\"SYS6\", instance=\"$host\"}",
     "legendFormat": "SYS6"
    },
    {
     "expr": "fmadio_fan_system{interface=\"SYS7\", instance=\"$host\"}",
     "legendFormat": "SYS6"
    }
   ]
  },
  {
   "title": "Disk Valid",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 29 },
   "targets": [
    {
     "expr": "fmadio_disk_valid{unit=\"hdd0\", instance=\"$host\"}",
     "legendFormat": "HDD0"
    },
    {
     "expr": "fmadio_disk_valid{unit=\"hdd1\", instance=\"$host\"}",
     "legendFormat": "HDD1"
    },
    {
     "expr": "fmadio_disk_valid{unit=\"hdd2\", instance=\"$host\"}",
     "legendFormat": "HDD2"
    },
    {
     "expr": "fmadio_disk_valid{unit=\"hdd3\", instance=\"$host\"}",
     "legendFormat": "HDD3"
    },
    {
     "expr": "fmadio_disk_valid{unit=\"hdd4\", instance=\"$host\"}",
     "legendFormat": "HDD4"
    },
    {
     "expr": "fmadio_disk_valid{unit=\"hdd5\", instance=\"$host\"}",
     "legendFormat": "HDD5"
    },
    {
     "expr": "fmadio_disk_valid{unit=\"hdd6\", instance=\"$host\"}",
     "legendFormat": "HDD6"
    },
    {
     "expr": "fmadio_disk_valid{unit=\"hdd7\", instance=\"$host\"}",
     "legendFormat": "HDD7"
    },
    {
     "expr": "fmadio_disk_valid{unit=\"hdd8\", instance=\"$host\"}",
     "legendFormat": "HDD8"
    },
    {
     "expr": "fmadio_disk_valid{unit=\"hdd9\", instance=\"$host\"}",
     "legendFormat": "HDD9"
    },
    {
     "expr": "fmadio_disk_valid{unit=\"hdd10\", instance=\"$host\"}",
     "legendFormat": "HDD10"
    },
    {
     "expr": "fmadio_disk_valid{unit=\"hdd11\", instance=\"$host\"}",
     "legendFormat": "HDD11"
    },
    {
     "expr": "fmadio_disk_valid{unit=\"hdd12\", instance=\"$host\"}",
     "legendFormat": "HDD12"
    },
    {
     "expr": "fmadio_disk_valid{unit=\"hdd13\", instance=\"$host\"}",
     "legendFormat": "HDD13"
    },
    {
     "expr": "fmadio_disk_valid{unit=\"hdd14\", instance=\"$host\"}",
     "legendFormat": "HDD14"
    },
    {
     "expr": "fmadio_disk_valid{unit=\"hdd15\", instance=\"$host\"}",
     "legendFormat": "HDD15"
    },
    {
     "expr": "fmadio_disk_valid{unit=\"ssd0\", instance=\"$host\"}",
     "legendFormat": "SSD0"
    },
    {
     "expr": "fmadio_disk_valid{unit=\"ssd1\", instance=\"$host\"}",
     "legendFormat": "SSD1"
    },
    {
     "expr": "fmadio_disk_valid{unit=\"ssd2\", instance=\"$host\"}",
     "legendFormat": "SSD2"
    },
    {
     "expr": "fmadio_disk_valid{unit=\"ssd3\", instance=\"$host\"}",
     "legendFormat": "SSD3"
    },
    {
     "expr": "fmadio_disk_valid{unit=\"ssd4\", instance=\"$host\"}",
     "legendFormat": "SSD4"
    },
    {
     "expr": "fmadio_disk_valid{unit=\"ssd5\", instance=\"$host\"}",
     "legendFormat": "SSD5"
    },
    {
     "expr": "fmadio_disk_valid{unit=\"ssd6\", instance=\"$host\"}",
     "legendFormat": "SSD6"
    },
    {
     "expr": "fmadio_disk_valid{unit=\"ssd7\", instance=\"$host\"}",
     "legendFormat": "SSD7"
    },
    {
     "expr": "fmadio_disk_valid{unit=\"ssd8\", instance=\"$host\"}",
     "legendFormat": "SSD8"
    },
    {
     "expr": "fmadio_disk_valid{unit=\"ssd9\", instance=\"$host\"}",
     "legendFormat": "SSD9"
    },
    {
     "expr": "fmadio_disk_valid{unit=\"ssd10\", instance=\"$host\"}",
     "legendFormat": "SSD10"
    },
    {
     "expr": "fmadio_disk_valid{unit=\"ssd11\", instance=\"$host\"}",
     "legendFormat": "SSD11"
    },
    {
     "expr": "fmadio_disk_valid{unit=\"ssd12\", instance=\"$host\"}",
     "legendFormat": "SSD12"
    },
    {
     "expr": "fmadio_disk_valid{unit=\"ssd13\", instance=\"$host\"}",
     "legendFormat": "SSD13"
    },
    {
     "expr": "fmadio_disk_valid{unit=\"ssd14\", instance=\"$host\"}",
     "legendFormat": "SSD14"
    },
    {
     "expr": "fmadio_disk_valid{unit=\"ssd15\", instance=\"$host\"}",
     "legendFormat": "SSD15"
    },
    {
     "expr": "fmadio_disk_valid{unit=\"ssd16\", instance=\"$host\"}",
     "legendFormat": "SSD16"
    },
    {
     "expr": "fmadio_disk_valid{unit=\"ssd17\", instance=\"$host\"}",
     "legendFormat": "SSD17"
    },
    {
     "expr": "fmadio_disk_valid{unit=\"ssd18\", instance=\"$host\"}",
     "legendFormat": "SSD18"
    },
    {
     "expr": "fmadio_disk_valid{unit=\"scr0\", instance=\"$host\"}",
     "legendFormat": "SCR0"
    },
    {
     "expr": "fmadio_disk_valid{unit=\"scr1\", instance=\"$host\"}",
     "legendFormat": "SCR1"
    },
    {
     "expr": "fmadio_disk_valid{unit=\"scr2\", instance=\"$host\"}",
     "legendFormat": "SCR2"
    },
    {
     "expr": "fmadio_disk_valid{unit=\"scr3\", instance=\"$host\"}",
     "legendFormat": "SCR3"
    },
    {
     "expr": "fmadio_disk_valid{unit=\"scr4\", instance=\"$host\"}",
     "legendFormat": "SCR4"
    },
    {
     "expr": "fmadio_disk_valid{unit=\"scr5\", instance=\"$host\"}",
     "legendFormat": "SCR5"
    },
    {
     "expr": "fmadio_disk_valid{unit=\"scr6\", instance=\"$host\"}",
     "legendFormat": "SCR6"
    },
    {
     "expr": "fmadio_disk_valid{unit=\"scr7\", instance=\"$host\"}",
     "legendFormat": "SCR7"
    },
    {
     "expr": "fmadio_disk_valid{unit=\"scr8\", instance=\"$host\"}",
     "legendFormat": "SCR8"
    },
    {
     "expr": "fmadio_disk_valid{unit=\"scr9\", instance=\"$host\"}",
     "legendFormat": "SCR9"
    },
    {
     "expr": "fmadio_disk_valid{unit=\"scr10\", instance=\"$host\"}",
     "legendFormat": "SCR10"
    },
    {
     "expr": "fmadio_disk_valid{unit=\"scr11\", instance=\"$host\"}",
     "legendFormat": "SCR11"
    },
    {
     "expr": "fmadio_disk_valid{unit=\"scr12\", instance=\"$host\"}",
     "legendFormat": "SCR12"
    },
    {
     "expr": "fmadio_disk_valid{unit=\"par0\", instance=\"$host\"}",
     "legendFormat": "PAR0"
    },
    {
     "expr": "fmadio_disk_valid{unit=\"par1\", instance=\"$host\"}",
     "legendFormat": "PAR1"
    },
    {
     "expr": "fmadio_disk_valid{unit=\"par2\", instance=\"$host\"}",
     "legendFormat": "PAR2"
    }
   ]
  },
  {
   "title": "Link Status",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 37 },
   "targets": [
    {
     "expr": "fmadio_link_up{interface=\"cap0\", instance=\"$host\"}",
     "legendFormat": "Cap0"
    },
    {
     "expr": "fmadio_link_up{interface=\"cap1\", instance=\"$host\"}",
     "legendFormat": "Cap1"
    },
    {
     "expr": "fmadio_link_up{interface=\"cap2\", instance=\"$host\"}",
     "legendFormat": "Cap2"
    },
    {
     "expr": "fmadio_link_up{interface=\"cap3\", instance=\"$host\"}",
     "legendFormat": "Cap3"
    },
    {
     "expr": "fmadio_link_up{interface=\"cap4\", instance=\"$host\"}",
     "legendFormat": "Cap4"
    },
    {
     "expr": "fmadio_link_up{interface=\"cap5\", instance=\"$host\"}",
     "legendFormat": "Cap5"
    },
    {
     "expr": "fmadio_link_up{interface=\"cap6\", instance=\"$host\"}",
     "legendFormat": "Cap6"
    },
    {
     "expr": "fmadio_link_up{interface=\"cap7\", instance=\"$host\"}",
     "legendFormat": "Cap7"
    },
    {
     "expr": "fmadio_link_up{interface=\"man0\", instance=\"$host\"}",
     "legendFormat": "Man0"
    },
    {
     "expr": "fmadio_link_up{interface=\"man10\", instance=\"$host\"}",
     "legendFormat": "Man10"
    }
   ]
  },
  {
   "title": "Disk Free (fmadio_disk_free)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "fmadio_disk_free{unit=\"store0\", instance=\"$host\"}",
     "legendFormat": "Store0"
    },
    {
     "expr": "fmadio_disk_free{unit=\"store1\", instance=\"$host\"}",
     "legendFormat": "Store1"
    },
    {
     "expr": "fmadio_disk_free{unit=\"remote0\", instance=\"$host\"}",
     "legendFormat": "Remote0"
    },
    {
     "expr": "fmadio_disk_free{unit=\"remote1\", instance=\"$host\"}",
     "legendFormat": "Remote1"
    },
    {
     "expr": "fmadio_disk_free{unit=\"system\", instance=\"$host\"}",
     "legendFormat": "System"
    }
   ]
  },
  {
   "title": "Power (Watt)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "fmadio_power_watt{instance=\"$host\"}",
     "legendFormat": "Power"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "fmadio_temperature{unit=\"cpu0\", instance=\"$host\"}",
     "legendFormat": "CPU0"
    },
    {
     "expr": "fmadio_temperature{unit=\"cpu1\", instance=\"$host\"}",
     "legendFormat": "CPU1"
    },
    {
     "expr": "fmadio_temperature{unit=\"airin\", instance=\"$host\"}",
     "legendFormat": "Air In"
    },
    {
     "expr": "fmadio_temperature{unit=\"airout\", instance=\"$host\"}",
     "legendFormat": "Air Out"
    },
    {
     "expr": "fmadio_temperature{unit=\"nic\", instance=\"$host\"}",
     "legendFormat": "NIC"
    },
    {
     "expr": "fmadio_temperature{unit=\"chipset\", instance=\"$host\"}",
     "legendFormat": "Chipset"
    },
    {
     "expr": "fmadio_temperature{unit=\"perhipherals\", instance=\"$host\"}",
     "legendFormat": "Perhipherals"
    },
    {
     "expr": "fmadio_temperature{unit=\"system\", instance=\"$host\"}",
     "legendFormat": "System"
    },
    {
     "expr": "fmadio_temperature{unit=\"transceiver0\", instance=\"$host\"}",
     "legendFormat": "Transceiver0"
    },
    {
     "expr": "fmadio_temperature{unit=\"transceiver1\", instance=\"$host\"}",
     "legendFormat": "Transceiver1"
    }
   ]
  },
  {
   "title": "PSU Status",
   "type": "state-timeline",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 53 },
   "targets": [
    {
     "expr": "fmadio_power_status{psu=\"0\", instance=\"$host\"}",
     "legendFormat": "PSU0"
    },
    {
     "expr": "fmadio_power_status{psu=\"1\", instance=\"$host\"}",
     "legendFormat": "PSU1"
    }
   ]
  },
  {
   "title": "Disk Temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "fmadio_temperature{unit=\"hdd0\", instance=\"$host\"}",
     "legendFormat": "HDD0"
    },
    {
     "expr": "fmadio_temperature{unit=\"hdd1\", instance=\"$host\"}",
     "legendFormat": "HDD1"
    },
    {
     "expr": "fmadio_temperature{unit=\"hdd2\", instance=\"$host\"}",
     "legendFormat": "HDD2"
    },
    {
     "expr": "fmadio_temperature{unit=\"hdd3\", instance=\"$host\"}",
     "legendFormat": "HDD3"
    },
    {
     "expr": "fmadio_temperature{unit=\"hdd4\", instance=\"$host\"}",
     "legendFormat": "HDD4"
    },
    {
     "expr": "fmadio_temperature{unit=\"hdd5\", instance=\"$host\"}",
     "legendFormat": "HDD5"
    },
    {
     "expr": "fmadio_temperature{unit=\"hdd6\", instance=\"$host\"}",
     "legendFormat": "HDD6"
    },
    {
     "expr": "fmadio_temperature{unit=\"hdd7\", instance=\"$host\"}",
     "legendFormat": "HDD7"
    },
    {
     "expr": "fmadio_temperature{unit=\"hdd8\", instance=\"$host\"}",
     "legendFormat": "HDD8"
    },
    {
     "expr": "fmadio_temperature{unit=\"ssd0\", instance=\"$host\"}",
     "legendFormat": "SSD0"
    },
    {
     "expr": "fmadio_temperature{unit=\"ssd1\", instance=\"$host\"}",
     "legendFormat": "SSD1"
    },
    {
     "expr": "fmadio_temperature{unit=\"ssd2\", instance=\"$host\"}",
     "legendFormat": "SSD2"
    },
    {
     "expr": "fmadio_temperature{unit=\"ssd3\", instance=\"$host\"}",
     "legendFormat": "SSD3"
    },
    {
     "expr": "fmadio_temperature{unit=\"ssd4\", instance=\"$host\"}",
     "legendFormat": "SSD4"
    },
    {
     "expr": "fmadio_temperature{unit=\"ssd5\", instance=\"$host\"}",
     "legendFormat": "SSD5"
    },
    {
     "expr": "fmadio_temperature{unit=\"ssd6\", instance=\"$host\"}",
     "legendFormat": "SSD6"
    },
    {
     "expr": "fmadio_temperature{unit=\"ssd7\", instance=\"$host\"}",
     "legendFormat": "SSD7"
    },
    {
     "expr": "fmadio_temperature{unit=\"ssd8\", instance=\"$host\"}",
     "legendFormat": "SSD8"
    },
    {
     "expr": "fmadio_temperature{unit=\"ssd9\", instance=\"$host\"}",
     "legendFormat": "SSD9"
    },
    {
     "expr": "fmadio_temperature{unit=\"ssd10\", instance=\"$host\"}",
     "legendFormat": "SSD10"
    },
    {
     "expr": "fmadio_temperature{unit=\"ssd11\", instance=\"$host\"}",
     "legendFormat": "SSD11"
    },
    {
     "expr": "fmadio_temperature{unit=\"ssd12\", instance=\"$host\"}",
     "legendFormat": "SSD12"
    },
    {
     "expr": "fmadio_temperature{unit=\"ssd13\", instance=\"$host\"}",
     "legendFormat": "SSD13"
    },
    {
     "expr": "fmadio_temperature{unit=\"ssd14\", instance=\"$host\"}",
     "legendFormat": "SSD14"
    },
    {
     "expr": "fmadio_temperature{unit=\"ssd15\", instance=\"$host\"}",
     "legendFormat": "SSD15"
    },
    {
     "expr": "fmadio_temperature{unit=\"ssd16\", instance=\"$host\"}",
     "legendFormat": "SSD16"
    },
    {
     "expr": "fmadio_temperature{unit=\"ssd17\", instance=\"$host\"}",
     "legendFormat": "SSD17"
    },
    {
     "expr": "fmadio_temperature{unit=\"ssd18\", instance=\"$host\"}",
     "legendFormat": "SSD18"
    },
    {
     "expr": "fmadio_temperature{unit=\"scr0\", instance=\"$host\"}",
     "legendFormat": "SCR0"
    },
    {
     "expr": "fmadio_temperature{unit=\"scr1\", instance=\"$host\"}",
     "legendFormat": "SCR1"
    },
    {
     "expr": "fmadio_temperature{unit=\"scr2\", instance=\"$host\"}",
     "legendFormat": "SCR2"
    },
    {
     "expr": "fmadio_temperature{unit=\"scr3\", instance=\"$host\"}",
     "legendFormat": "SCR3"
    },
    {
     "expr": "fmadio_temperature{unit=\"scr4\", instance=\"$host\"}",
     "legendFormat": "SCR4"
    },
    {
     "expr": "fmadio_temperature{unit=\"scr5\", instance=\"$host\"}",
     "legendFormat": "SCR5"
    },
    {
     "expr": "fmadio_temperature{unit=\"scr6\", instance=\"$host\"}",
     "legendFormat": "SCR6"
    },
    {
     "expr": "fmadio_temperature{unit=\"scr7\", instance=\"$host\"}",
     "legendFormat": "SCR7"
    },
    {
     "expr": "fmadio_temperature{unit=\"scr8\", instance=\"$host\"}",
     "legendFormat": "SCR8"
    },
    {
     "expr": "fmadio_temperature{unit=\"scr9\", instance=\"$host\"}",
     "legendFormat": "SCR9"
    },
    {
     "expr": "fmadio_temperature{unit=\"scr10\", instance=\"$host\"}",
     "legendFormat": "SCR10"
    },
    {
     "expr": "fmadio_temperature{unit=\"scr11\", instance=\"$host\"}",
     "legendFormat": "SCR11"
    },
    {
     "expr": "fmadio_temperature{unit=\"scr12\", instance=\"$host\"}",
     "legendFormat": "SCR12"
    },
    {
     "expr": "fmadio_temperature{unit=\"par0\", instance=\"$host\"}",
     "legendFormat": "PAR0"
    },
    {
     "expr": "fmadio_temperature{unit=\"par1\", instance=\"$host\"}",
     "legendFormat": "PAR1"
    }
   ]
  },
  {
   "title": "Clock",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 61 },
   "collapsed": true,
   "panels": [
    {
     "title": "Clock Offset",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "ns" } },
     "targets": [
      {
       "expr": "fmadio_ptp_Clk156Offset{instance=\"$host\"}",
       "legendFormat": "Clk156 Offset"
      },
      {
       "expr": "fmadio_ptp_GMOffset{instance=\"$host\"}",
       "legendFormat": "GM Offset"
      },
      {
       "expr": "fmadio_ptp_Clk250Offset{instance=\"$host\"}",
       "legendFormat": "Clk250 Offset"
      },
      {
       "expr": "fmadio_ptp_Clk322Offset{instance=\"$host\"}",
       "legendFormat": "Clk322 Offset"
      },
      {
       "expr": "fmadio_ptp_NTPOffset{instance=\"$host\"}",
       "legendFormat": "NTP Offset"
      },
      {
       "expr": "fmadio_ptp_PPSOffset{instance=\"$host\"}",
       "legendFormat": "PPS Offset"
      },
      {
       "expr": "fmadio_ptp_SysOffset{instance=\"$host\"}",
       "legendFormat": "SYS Offset"
      }
     ]
    },
    {
     "title": "PPS Counter",
     "type": "stat",
     "gridPos": { "h": 3, "w": 2, "x": 12, "y": 2 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "fmadio_ptp_PPSCnt{instance=\"$host\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 3, "w": 7, "x": 14, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "fmadio_ptp_GMUpTime{instance=\"$host\"}",
       "legendFormat": "GM Uptime"
      },
      {
       "expr": "fmadio_ptp_NTPUptime{instance=\"$host\"}",
       "legendFormat": "NTP Uptime"
      },
      {
       "expr": "fmadio_ptp_PPSUptime{instance=\"$host\"}",
       "legendFormat": "PPS Uptime"
      },
      {
       "expr": "fmadio_ptp_SysUptime{instance=\"$host\"}",
       "legendFormat": "SYS Uptime"
      }
     ]
    }
   ]
  },
  {
   "title": "Stream Cat Information",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 62 },
   "collapsed": true,
   "panels": [
    {
     "title": "Stream CAT Status",
     "type": "state-timeline",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 11 },
     "targets": [
      {
       "expr": "fmadio_cat_enable{ioqueue=\"0\", instance=\"$host\"}",
       "legendFormat": "cat0"
      },
      {
       "expr": "fmadio_cat_enable{ioqueue=\"1\", instance=\"$host\"}",
       "legendFormat": "cat1"
      },
      {
       "expr": "fmadio_cat_enable{ioqueue=\"2\", instance=\"$host\"}",
       "legendFormat": "cat2"
      },
      {
       "expr": "fmadio_cat_enable{ioqueue=\"3\", instance=\"$host\"}",
       "legendFormat": "cat3"
      },
      {
       "expr": "fmadio_cat_enable{ioqueue=\"4\", instance=\"$host\"}",
       "legendFormat": "cat4"
      },
      {
       "expr": "fmadio_cat_enable{ioqueue=\"5\", instance=\"$host\"}",
       "legendFormat": "cat5"
      },
      {
       "expr": "fmadio_cat_enable{ioqueue=\"6\", instance=\"$host\"}",
       "legendFormat": "cat6"
      },
      {
       "expr": "fmadio_cat_enable{ioqueue=\"7\", instance=\"$host\"}",
       "legendFormat": "cat7"
      }
     ]
    },
    {
     "title": "cat write rate using total field",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "bps" } },
     "targets": [
      {
       "expr": "increase(fmadio_cat_write_byte_total{ioqueue=\"0\", instance=\"$host\"}[$__interval])*8",
       "legendFormat": "stream0"
      },
      {
       "expr": "increase(fmadio_cat_write_byte_total{ioqueue=\"1\", instance=\"$host\"}[$__interval])*8",
       "legendFormat": "stream1"
      },
      {
       "expr": "increase(fmadio_cat_write_byte_total{ioqueue=\"2\", instance=\"$host\"}[$__interval])*8",
       "legendFormat": "stream2"
      },
      {
       "expr": "increase(fmadio_cat_write_byte_total{ioqueue=\"3\", instance=\"$host\"}[$__interval])*8",
       "legendFormat": "stream3"
      },
      {
       "expr": "increase(fmadio_cat_write_byte_total{ioqueue=\"4\", instance=\"$host\"}[$__interval])*8",
       "legendFormat": "stream4"
      },
      {
       "expr": "increase(fmadio_cat_write_byte_total{ioqueue=\"5\", instance=\"$host\"}[$__interval])*8",
       "legendFormat": "stream5"
      },
      {
       "expr": "increase(fmadio_cat_write_byte_total{ioqueue=\"6\", instance=\"$host\"}[$__interval])*8",
       "legendFormat": "stream6"
      },
      {
       "expr": "increase(fmadio_cat_write_byte_total{ioqueue=\"7\", instance=\"$host\"}[$__interval])*8",
       "legendFormat": "stream7"
      }
     ]
    },
    {
     "title": "cat write pkt",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "expr": "fmadio_cat_write_pkt{ioqueue=\"0\", instance=\"$host\"}",
       "legendFormat": "stream0"
      },
      {
       "expr": "fmadio_cat_write_pkt{ioqueue=\"1\", instance=\"$host\"}",
       "legendFormat": "stream1"
      },
      {
       "expr": "fmadio_cat_write_pkt{ioqueue=\"2\", instance=\"$host\"}",
       "legendFormat": "stream2"
      },
      {
       "expr": "fmadio_cat_write_pkt{ioqueue=\"3\", instance=\"$host\"}",
       "legendFormat": "stream3"
      },
      {
       "expr": "fmadio_cat_write_pkt{ioqueue=\"4\", instance=\"$host\"}",
       "legendFormat": "stream4"
      },
      {
       "expr": "fmadio_cat_write_pkt{ioqueue=\"5\", instance=\"$host\"}",
       "legendFormat": "stream5"
      },
      {
       "expr": "fmadio_cat_write_pkt{ioqueue=\"6\", instance=\"$host\"}",
       "legendFormat": "stream6"
      },
      {
       "expr": "fmadio_cat_write_pkt{ioqueue=\"7\", instance=\"$host\"}",
       "legendFormat": "stream7"
      }
     ]
    },
    {
     "title": "cat write rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "bps" } },
     "targets": [
      {
       "expr": "(fmadio_cat_write_byte{ioqueue=\"0\", instance=\"$host\"})*8",
       "legendFormat": "stream0"
      },
      {
       "expr": "(fmadio_cat_write_byte{ioqueue=\"1\", instance=\"$host\"})*8",
       "legendFormat": "stream1"
      },
      {
       "expr": "(fmadio_cat_write_byte{ioqueue=\"2\", instance=\"$host\"})*8",
       "legendFormat": "stream2"
      },
      {
       "expr": "(fmadio_cat_write_byte{ioqueue=\"3\", instance=\"$host\"})*8",
       "legendFormat": "stream3"
      },
      {
       "expr": "(fmadio_cat_write_byte{ioqueue=\"4\", instance=\"$host\"})*8",
       "legendFormat": "stream4"
      },
      {
       "expr": "(fmadio_cat_write_byte{ioqueue=\"5\", instance=\"$host\"})*8",
       "legendFormat": "stream5"
      },
      {
       "expr": "(fmadio_cat_write_byte{ioqueue=\"6\", instance=\"$host\"})*8",
       "legendFormat": "stream6"
      },
      {
       "expr": "(fmadio_cat_write_byte{ioqueue=\"7\", instance=\"$host\"})*8",
       "legendFormat": "stream7"
      }
     ]
    },
    {
     "title": "cat read pkt",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "expr": "increase(fmadio_cat_read_pkt{ioqueue=\"0\", instance=\"$host\"}[$__interval])",
       "legendFormat": "stream0"
      },
      {
       "expr": "increase(fmadio_cat_read_pkt{ioqueue=\"1\", instance=\"$host\"}[$__interval])",
       "legendFormat": "stream1"
      },
      {
       "expr": "increase(fmadio_cat_read_pkt{ioqueue=\"2\", instance=\"$host\"}[$__interval])",
       "legendFormat": "stream2"
      },
      {
       "expr": "increase(fmadio_cat_read_pkt{ioqueue=\"3\", instance=\"$host\"}[$__interval])",
       "legendFormat": "stream3"
      },
      {
       "expr": "increase(fmadio_cat_read_pkt{ioqueue=\"4\", instance=\"$host\"}[$__interval])",
       "legendFormat": "stream4"
      },
      {
       "expr": "increase(fmadio_cat_read_pkt{ioqueue=\"5\", instance=\"$host\"}[$__interval])",
       "legendFormat": "stream5"
      },
      {
       "expr": "increase(fmadio_cat_read_pkt{ioqueue=\"6\", instance=\"$host\"}[$__interval])",
       "legendFormat": "stream6"
      },
      {
       "expr": "increase(fmadio_cat_read_pkt{ioqueue=\"7\", instance=\"$host\"}[$__interval])",
       "legendFormat": "stream7"
      }
     ]
    },
    {
     "title": "cat read bytes",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "increase(fmadio_cat_read_byte_total{ioqueue=\"0\", instance=\"$host\"}[$__interval])*8",
       "legendFormat": "stream0"
      },
      {
       "expr": "increase(fmadio_cat_read_byte_total{ioqueue=\"1\", instance=\"$host\"}[$__interval])*8",
       "legendFormat": "stream1"
      },
      {
       "expr": "increase(fmadio_cat_read_byte_total{ioqueue=\"2\", instance=\"$host\"}[$__interval])*8",
       "legendFormat": "stream2"
      },
      {
       "expr": "increase(fmadio_cat_read_byte_total{ioqueue=\"3\", instance=\"$host\"}[$__interval])*8",
       "legendFormat": "stream3"
      },
      {
       "expr": "increase(fmadio_cat_read_byte_total{ioqueue=\"4\", instance=\"$host\"}[$__interval])*8",
       "legendFormat": "stream4"
      },
      {
       "expr": "increase(fmadio_cat_read_byte_total{ioqueue=\"5\", instance=\"$host\"}[$__interval])*8",
       "legendFormat": "stream5"
      },
      {
       "expr": "increase(fmadio_cat_read_byte_total{ioqueue=\"6\", instance=\"$host\"}[$__interval])*8",
       "legendFormat": "stream6"
      },
      {
       "expr": "increase(fmadio_cat_read_byte_total{ioqueue=\"7\", instance=\"$host\"}[$__interval])*8",
       "legendFormat": "stream7"
      }
     ]
    }
   ]
  },
  {
   "title": "Row title",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 63 },
   "collapsed": true
  }
 ]
}